ALTER TABLE `products`
  ADD COLUMN `english_name` VARCHAR(255) NULL,
  ADD COLUMN `chinese_name` VARCHAR(255) NULL,
  ADD COLUMN `brand_name` VARCHAR(80) NULL,
  ADD COLUMN `category_name` VARCHAR(120) NULL;

CREATE TABLE `pos_product_candidates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` BIGINT UNSIGNED NOT NULL,
  `store_id` BIGINT UNSIGNED NOT NULL,
  `external_product_id` VARCHAR(64) NOT NULL,
  `source_sku` VARCHAR(64) NULL,
  `barcode` VARCHAR(128) NOT NULL,
  `source_name` VARCHAR(255) NOT NULL,
  `english_name` VARCHAR(255) NOT NULL,
  `chinese_name` VARCHAR(255) NULL,
  `brand_name` VARCHAR(80) NULL,
  `category_name` VARCHAR(120) NULL,
  `item_type` VARCHAR(32) NULL,
  `sale_price` DECIMAL(14, 2) NULL,
  `cost_price` DECIMAL(14, 2) NULL,
  `source_stock` DECIMAL(14, 4) NULL,
  `source_status` VARCHAR(32) NULL,
  `review_status` ENUM('PENDING', 'APPROVED', 'IGNORED') NOT NULL DEFAULT 'PENDING',
  `translation_status` ENUM('UNTRANSLATED', 'DRAFT', 'APPROVED') NOT NULL DEFAULT 'UNTRANSLATED',
  `last_review_request_id` VARCHAR(64) NULL,
  `reviewed_at` DATETIME(3) NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `first_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `pos_product_candidates_store_id_external_product_id_key` (`store_id`, `external_product_id`),
  UNIQUE INDEX `pos_product_candidates_last_review_request_id_key` (`last_review_request_id`),
  INDEX `pos_product_candidates_store_id_status_review_status_idx` (`store_id`, `status`, `review_status`),
  INDEX `pos_product_candidates_organization_id_barcode_idx` (`organization_id`, `barcode`),
  INDEX `pos_product_candidates_store_id_translation_status_idx` (`store_id`, `translation_status`),
  PRIMARY KEY (`id`),
  CONSTRAINT `pos_product_candidates_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pos_product_candidates_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
